name: Docker Build And Push To Docker Hub

on:
  push:
    branches:
    - master 
#   schedule:
#     - cron: '0 10 * * *' # everyday at 10am
#   push:
#     tags:
#       - 'v*.*.*'
#  pull_request:

env:
  DOCKER_REPOSITORY: webase-front
  DOCKER_FISCO_TAG: v2.8.0
  DOCKER_FISCO_REPOSITORY: fisco-webase


jobs:
  # webase-front
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: clean build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_WEBASEPRO_USERNAME }}
          password: ${{ secrets.DOCKER_WEBASEPRO_TOKEN }}

            # - name: Copy nginx config file
            #   id: copy-nginx-file
            #   run: |
            #     cp ./docker/weoracle-web.conf dist/

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./dist
          push: true
          file: ./docker/build/Dockerfile
          platforms: linux/amd64
          tags: v3.0.0

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

